### ISSUE TITLE
Wrong fixed amount being paid.

### ISSUE THREAD

**Issue by Wissi** [Flibio/PayDay#1]
@Flibio well, it seems to be paying. The problem is that everyone is being paid 70.00 regardless of the "group" they belong to.  Using Permission Manager  (PermissionManager-2.6.0-API-5.X-6.X.jar)  to create/manage groups.

```
timeamount="15"
timeunit=Minutes
payamounts={
    "Guest"= {
        "permission"= "*",
        "amount"= 10.0
    },
    "Newbie"= {
        "permission"= "*",
        "amount"= 20.0
    },
    "Rookie"= {
        "permission"= "*",
        "amount"= 30.0
    },
    "Trainee"= {
        "permission"= "*",
        "amount"= 40.0
    },
    "Member"= {
        "permission"= "*",
        "amount"= 50.0
    },
    "Citizen"= {
        "permission"= "*",
        "amount"= 60.0
    },
    "Colonist"= {
        "permission"= "*",
        "amount"= 70.0
    },
    "Mayor"= {
        "permission"= "*",
        "amount"= 80.0
    },
    "Governor"= {
        "permission"= "*",
        "amount"= 90.0
    },
    "Veteran"= {
        "permission"= "*",
        "amount"= 100.0
    },
    "Royal"= {
        "permission"= "*",
        "amount"= 110.0
    },
    "Patreon"= {
        "permission"= "*",
        "amount"= 50.0
    },
    "Patreon"= {
        "permission"= "*",
        "amount"= 50.0
    },
    "Mod"= {
        "permission"= "*",
        "amount"= 100.0
    },
    "Admin"= {
        "permission"= "*",
        "amount"= 100.0
    }
}
```

**Comment by Flibio** [comment]
That actually isn't quite how groups work - The group name really makes no difference, it is the permission that matters. Since all of your permissions are `*`, that means everyone is paid. You need to type in a permission besides `*` in the permission field, and then assign that permission to a PermissionManager group.

**Comment by Wissi** [comment]
Yes, you are right. I misread and misunderstood. It works as intended. thank you very much.
If we find any issues I'll let you know as well as any features.

Thank you very much for all your work on both plugins.

**Comment by Flibio** [comment]
@Wissi: No problem, I'll look into how I can modify the post to make the usage more clear to users.
