### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by PixelmonPRO** [Flibio/PayDay#3]
Hello! Please, add localization messages in config file :)

**Comment by Flibio** [comment]
I'll look into adding it when I have time.

**Comment by PixelmonPRO** [comment]
@Flibio Any news?)

**Comment by Flibio** [comment]
I haven't done it yet, hopefully sometime soon.

**Comment by PixelmonPRO** [comment]
Translated for myself and collected the source code in IDEA
