### ISSUE TITLE
[Request] Working with AFK Characters

### ISSUE THREAD

**Issue by AtaxiaGames-GM** [Flibio/PayDay#4]
Could you please add a configuration to stop the timer for characters in AFK status?

Thank you for your time and consideration!

**Comment by Flibio** [comment]
How is AFK status defined? Do you want PayDay to hook into another plugin? I'm not quite sure what you mean by this.

**Comment by AtaxiaGames-GM** [comment]
AFK is defined by the Nucleus plugin. I am wondering if, when the AFK flag is set to true for a given player PayDay should stop that character's PayDay clock.

As it is right now, I have the Nucleus plugin automatically kick any player whose AFK timer reaches 15 minutes. The only reason why I have that setup is to prevent players from just being able to leave their character idle while still accumulating currency provided by the PayDay plugin.

I appreciate your response; thank you!

**Comment by Flibio** [comment]
I'll take a look at it when I have time.

**Comment by AtaxiaGames-GM** [comment]
Thank you again!

**Comment by Flibio** [comment]
9f1690f5a7c25fc221710f641756d88145a3ba4f
