### ISSUE TITLE
Login pay glitch.

### ISSUE THREAD

**Issue by Wissi** [Flibio/PayDay#5]
hey Flibio, thanx for the work. Awesome simple mod, we love it. 
Recently there is and issue that whenever a player logs in they get automatically paid. If they logout and immediately login, they get paid again. So players can login/logout/login as many times as they want and are getting paid every time they login (which defeats the timer restriction).

Using latest PayDay-1.0.0.jar on SpongeForge spongeforge-1.10.2-2281-5.2.0-BETA-2424.jar

**Comment by Flibio** [comment]
If you would like, you can disable paying on join by setting the `payonjoin` option in the configuration file to false.

**Comment by Wissi** [comment]
Do I add that entire line to the Config? There is currently NO "payonjoin" option in the config.  
Example:
``
timeamount="15"
timeunit=Minutes
payamounts={
    "Guest"= {
        "permission"= "payday.guest",
        "amount"= 10.0
    }
}
``

**Comment by Flibio** [comment]
What version of PayDay are you running? The option should have been generated.

**Comment by Wissi** [comment]
Using latest PayDay-1.0.0.jar on SpongeForge spongeforge-1.10.2-2281-5.2.0-BETA-2424.jar
And nope, no option generated.

**Comment by Wissi** [comment]
I see that ver. 1.1.0 has that update. going to update to disable payonjoin.  
Thanks.

**Comment by Wissi** [comment]
BTW.. thank you so much for all your quick responses always.
I forgot to lookup the update you had already and next ver.  1.1.0  has that specific change.

Thank you so much.
