### ISSUE TITLE
payday.conf doesn't generate fully

### ISSUE THREAD

**Issue by fcpwiz** [Flibio/PayDay#6]
PayDay version: tested on 1.1.0 and 1.2.0, this issue is present on both
SpongeForge version: spongeforge-1.10.2-2281-5.2.0-BETA-2433.jar

This is all payday.conf generates:
```
payonjoin="true"
timeamount="1"
timeunit=Hours

```

**Comment by Flibio** [comment]
Are there any error messages in the console? Can you also try re-downloading version 1.2.0? Also please try deleting the config file and see if that fixes it.

**Comment by fcpwiz** [comment]
@Flibio I've already tried redownloading and regenerating the config file.

Also, I just looked through fml-server-latest.log by searching "PayDay" but no error came up.

**Comment by Flibio** [comment]
I see what the issue is, I'll try to have a fix out shortly.

**Comment by fcpwiz** [comment]
@Flibio great, thank you!

**Comment by Flibio** [comment]
e51a373c73aa66e4936731f1166487660bc2a15e

**Comment by fcpwiz** [comment]
@Flibio Ok, I'm running 1.2.1 and this is the config I'm getting:

```
enableafkpay="true"
payonjoin="true"
timeamount="1"
timeunit=Hours

```

**Comment by Flibio** [comment]
That is correct, the other section on payments must be added yourself. Just read the usage section on GitHub or Ore!

**Comment by fcpwiz** [comment]
Ah, ok thank you!

**Comment by fcpwiz** [comment]
@Flibio So would this config work properly?

```
enableafkpay="true"
payonjoin="true"
timeamount="1"
timeunit=Hours
payamounts={
    "players"= {
        "permission"= "payday.pay.newbie",
        "amount"= 50.0
    }
}
```

**Comment by Flibio** [comment]
I think that should do the trick, let me know if you have any more issues!

**Comment by fcpwiz** [comment]
Also, are you sure 

```
payamounts={
    "players"= {
        "permission"= "*",
        "amount"= 50.0
    }
}
``` 

Isn't supposed to generate automatically? You have to add that^ manually?

**Comment by fcpwiz** [comment]
<img width="922" alt="flibio_payday__this_is_a_simple_sponge_plugin_that_gives_players_money_every_hour_" src="https://user-images.githubusercontent.com/2921172/28248320-ee9d3170-6a10-11e7-9d6a-9d863a827c7a.png">

Beacause on your repo, that's what's there.

**Comment by Flibio** [comment]
It does not generate automatically, that is just an example configuration to show users how to use the plugin. I suppose someday I might add it to be generated.

**Comment by fcpwiz** [comment]
Ah, alright. Thanks for the fix!

**Comment by fcpwiz** [comment]
@Flibio One more question - how do I reload your plugin?

**Comment by Flibio** [comment]
Right now you must restart the server. Due to how the payment scheduling works, reloading is not very feasible and would cause issues.
