### ISSUE TITLE
Api 7 Compatibility?

### ISSUE THREAD

**Issue by Wissi** [Flibio/PayDay#7]
Hi, we love the plugin been using on our server for a while now.
Will you be porting over to API 7?
We're moving over to 1.12 and would love to keep using your plugin.

Thanks for your awesome work.

**Comment by Flibio** [comment]
I'm a bit busy with other things right now. I'll try to get an update out in the next few days. For sure by the end of next weekend.

**Comment by Wissi** [comment]
That's awesome!

Thank you so much.

**Comment by Flibio** [comment]
07c2639224431c32b7df74ce3c6e0947d0ef9c7b

**Comment by Wissi** [comment]
Seems to be working great!

Thanks for such quick fix and reply. 
If any issues we'll sure let you know.
