### ISSUE TITLE
[Request] Payday Message

### ISSUE THREAD

**Issue by yepidoodles** [Flibio/PayDay#8]
Hello!

Currently when you get paid, you get the following message:
[![Screenshot from Gyazo](https://gyazo.com/a3d78110807bf1fbb70ac96cae73c4af/raw)](https://gyazo.com/a3d78110807bf1fbb70ac96cae73c4af)
As you can see, the message spills onto the following line by only one word, which isn't all that necessary, so my request is to remove the "Enjoy!" to make the message a single line, or creating a config for it so we can edit it ourselves.

Many thanks

Alice
DragonTechMC

P.S. Great plugin, good work.

**Comment by Flibio** [comment]
I will take a look at doing this.

**Comment by Flibio** [comment]
19b2115e5be1d2986a6111ed071110eb7de4aea8
